export const CHAT_MODES = {
  NORMAL_PREVIEW: 'NORMAL_PREVIEW_CHAT_MODE',
  FAVORITE_PREVIEW: 'FAVORITE_PREVIEW_CHAT_MODE',
  BLOCKED_PREVIEW: 'BLOCKED_PREVIEW_CHAT_MODE',
  CATALOG_PREVIEW: 'CATALOG_PREVIEW_CHAT_MODE',
};

export const CHAT_ACTIONS = {
  CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
  ADD_CHAT_TO_OLD_CATALOG: 'ADD_CHAT_TO_OLD_CATALOG',
  CREATE_NEW_CATALOG_AND_ADD_CHAT: 'CREATE_NEW_CATALOG_AND_ADD_CHAT',
};
